<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-10-08T18:04:40+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'locale' => 'ja_JP',
    'site' => 'カンパイ本町',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1475396863,
        'latest_version' => '5.7.5.9',
        'do_page_reindex_check' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 1,
    ),
);
